"""Canonical V2 configuration parsing and schema primitives."""

from .models import (
    AccessConfiguration,
    BrainConfiguration,
    BundleManifest,
    HouseholdConfiguration,
    OPTIONAL_ROLE_MODELS,
    REQUIRED_ROLE_MODELS,
    ROLE_MODELS,
    SatellitesConfiguration,
    validate_required_role,
    validate_role,
)
from .access_safety import (
    ACCESS_SCHEMA_FIELD_DISPOSITIONS,
    access_schema_field_paths,
    classify_access_safety,
    intrinsic_access_acknowledgements,
)
from .loader import (
    AUTHORED_REVISION_PREFIX,
    AuthoredCandidateSnapshot,
    AuthoredRevisionConflict,
    LoadedBundle,
    assert_authored_revision,
    load_bundle,
    load_bundle_snapshot,
    load_bundle_snapshot_structure,
    snapshot_candidate,
    validate_loaded_bundle,
)
from .diff import SemanticChange, semantic_diff
from .generations import (
    ACTIVATION_GENERATION_FORMAT,
    CONFIG_GENERATION_FORMAT,
    SECRET_GENERATION_FORMAT,
    SECRET_STATUS_FORMAT,
    SELECTED_POINTER_FORMAT,
    STORE_FORMAT,
    ActivationGeneration,
    ConfigGeneration,
    GenerationCompatibilityError,
    GenerationIntegrityError,
    GenerationStore,
    GenerationStoreError,
    SecretGeneration,
    SecretGenerationPrunedError,
    SecretGenerationRevokedError,
    SelectedActivation,
    StoreLineageConflict,
)
from .normalization import (
    CONFIG_FORMAT,
    CONFIG_REVISION_PREFIX,
    ConfigurationCanonicalizationError,
    NormalizedBundle,
    canonicalize_json,
    normalize_bundle,
)
from .roles import (
    BundleRoleError,
    BundleRoleInventory,
    OPTIONAL_ROLE_PATHS,
    REQUIRED_ROLE_PATHS,
    discover_bundle_roles,
)
from .provenance import ProvenanceEntry, collect_provenance
from .reporting import CandidateInspection, ValidationReport, inspect_candidate
from .effective import EffectiveConfig, load_effective_config
from .brain_runtime_settings import (
    BrainRuntimeSettings,
    SelectedInferenceConfiguration,
    SelectedSttConfiguration,
    SelectedTtsConfiguration,
)
from .brain_effective_runtime_settings import BrainEffectiveRuntimeSettings
from .brain_core_runtime_consumers import (
    BrainCoreRuntimeConsumers,
)
from .household_runtime_settings import HouseholdRuntimeSettings
from .access_runtime_settings import (
    AccessRuntimeSettings,
    SourceCredentialBindingSettings,
)
from .satellite_fleet_runtime_settings import (
    SatelliteBrainEdgeSettings,
    SatelliteFleetRuntimeSettings,
)
from .satellite_ui_runtime_settings import (
    SatelliteUiRuntimeEntry,
    SatelliteUiRuntimeSettings,
)
from .information_runtime_settings import (
    FactsRuntimeSettings,
    InformationRuntimeSettings,
    NewsRuntimeSettings,
    NewsSourceRuntimeSettings,
    SuggestionsRuntimeSettings,
)
from .music_runtime_settings import MusicRuntimeSettings
from .audiobook_runtime_settings import (
    AudiobookRuntimeSettings,
    AudiobookUserAccountSettings,
)
from .weather_runtime_settings import (
    CurrentWeatherRuntimeSettings,
    ForecastWeatherRuntimeSettings,
    HistoryWeatherRuntimeSettings,
    RemoteWeatherRuntimeSettings,
    WeatherHistorySshRuntimeSettings,
    WeatherRuntimeSettings,
)
from .calendar_runtime_settings import (
    CalendarFeedRuntimeSettings,
    CalendarReadRuntimeSettings,
    CalendarRuntimeSettings,
    CalendarWriteRuntimeSettings,
)
from .home_assistant_runtime_settings import (
    HomeAssistantAutomationRuntimeSettings,
    HomeAssistantRuntimeSettings,
)
from .notification_runtime_settings import (
    NotificationProviderRuntimeSettings,
    NotificationRecipientGroupRuntimeSettings,
    NotificationRuntimeSettings,
    NotificationTypeRuntimeSettings,
)
from .routine_runtime_settings import (
    RoutineDefinitionRuntimeSettings,
    RoutineRuntimeSettings,
    RoutineStepRuntimeSettings,
)
from .network_inventory_runtime_settings import (
    NetworkDependencyRuntimeSettings,
    NetworkDeviceRuntimeSettings,
    NetworkInventoryRuntimeSettings,
    NetworkMonitorRuntimeSettings,
    NetworkPowerTargetRuntimeSettings,
    NetworkServiceGroupRuntimeSettings,
    NetworkServiceRuntimeSettings,
)
from .network_adapter_runtime_settings import (
    NetworkAdapterRuntimeSettings,
    NetworkAdaptersRuntimeSettings,
)
from .network_policy_runtime_settings import (
    NetworkActionRuntimeSettings,
    NetworkPolicyRuntimeSettings,
    NetworkRecoveryRuntimeSettings,
)
from .runtime_cutover import (
    RUNTIME_CUTOVER_FORMAT,
    RUNTIME_CUTOVER_PATH,
    RuntimeCutoverMarker,
    arm_runtime_cutover,
    load_runtime_cutover_marker,
    runtime_cutover_required,
)
from .projections import (
    ControlServiceCompatibility,
    PROJECTION_REVISION_PREFIX,
    PROJECTION_SCHEMA_VERSION,
    GeneratedSatelliteProjection,
    InteractionRuntimeCompatibility,
    AcceptedSatelliteRuntimeCompatibility,
    ProjectedMusicConfiguration,
    ProjectionGenerationError,
    SatelliteProjectedConfiguration,
    SatelliteProjection,
    SatelliteRuntimeCompatibility,
    SatelliteRuntimeCompatibilityStore,
    generate_satellite_projection,
)
from .projection_generations import (
    PROJECTION_ACTIVATION_FORMAT,
    PROJECTION_GENERATION_FORMAT,
    PROJECTION_SECRET_GENERATION_FORMAT,
    InstalledSatelliteProjection,
    SatelliteProjectionActivation,
    SatelliteProjectionGeneration,
    SatelliteProjectionGenerationStore,
    SatelliteProjectionSecretGeneration,
)
from .projection_resolution import (
    SATELLITE_PROJECTION_PULL_FORMAT,
    ResolvedSatelliteProjection,
    SatelliteProjectionAuthenticationError,
    SatelliteProjectionPullEnvelope,
    SatelliteProjectionResolver,
)
from .playback_target_resolution import (
    CanonicalPlaybackTargetResolver,
    PlaybackTargetResolutionError,
    ResolvedPlaybackTarget,
)
from .request_source_resolution import (
    EPHEMERAL_HTTP_SOURCE_ID,
    CanonicalRequestSourceResolver,
    RequestSourceAuthenticationError,
    ResolvedRequestSource,
)
from .secrets import (
    SecretCompanionError,
    SecretReferenceUse,
    SecretSnapshot,
    collect_secret_references,
    load_secret_companion,
    parse_secret_companion,
    validate_secret_snapshot,
)
from .secret_transactions import (
    SecretAlreadyExists,
    SecretCompanionDrift,
    SecretMutationError,
    SecretMutationResult,
    SecretMutationUnavailable,
    SecretNotFound,
    SecretRemovalBlocked,
)
from .authoring_transactions import (
    AUTHORING_TRANSACTION_FORMAT,
    AuthoringModeError,
    AuthoringMutationError,
    AuthoringMutationUnavailable,
)
from .service import (
    AUDIT_FORMAT,
    REPORT_FORMAT,
    CandidateActivationBlocked,
    AuthoringMutationResult,
    CandidateReview,
    ConfigurationStatus,
    RuntimeCutoverResult,
    SatelliteRuntimeCompatibilityAcceptanceResult,
    ConfigurationService,
    ConfigurationTransactionResult,
    ExclusiveStoreLock,
    SecretGenerationConflict,
    SafetyAcknowledgementRequired,
    SelectedGenerationChanged,
    StoreLockTimeout,
    TransitionActivationBlocked,
    VALIDATION_VERSION,
)
from .host_local import (
    HOST_LOCAL_PROTOCOL_FORMAT,
    HostLocalAuthorizationError,
    HostLocalConfigurationClient,
    HostLocalConfigurationServer,
    HostLocalDispatcher,
    HostLocalProtocolError,
    HostLocalServiceAlreadyRunning,
    ServicePresenceLock,
    StandardUnixPeerAuthorizer,
    UnixPeerCredentials,
    UnixPeerIdentity,
    candidate_role_text,
    read_unix_peer_credentials,
)
from .selection_transactions import (
    SELECTION_TRANSACTION_FORMAT,
    SelectionCommittedAuditPending,
    SelectionRecoveryAmbiguous,
    SelectionTransactionEnvelope,
    SelectionTransactionJournal,
)
from .transition_validation import (
    TransitionValidationContext,
    TransitionValidationResult,
    validate_configuration_transition,
)
from .bootstrap import (
    CONFIGURATION_BOOTSTRAP_ENV_NAMES,
    STANDARD_INSTALLATION_ENV,
    BrainConfigurationHostLocalRuntime,
    BrainConfigurationStartup,
    ConfigurationBootstrapError,
    ConfigurationBootstrapSettings,
    StandardBrainConfigurationHostLocalRuntime,
    load_standard_installation_effective_config,
    resolve_brain_configuration_startup,
    start_brain_configuration_host_local_runtime,
)
from .yaml_parser import ConfigurationSyntaxError, ParsedYamlDocument, RestrictedYamlParser
from .validation import BundleValidationError, ConfigurationFinding

__all__ = [
    "ACCESS_SCHEMA_FIELD_DISPOSITIONS",
    "AUDIT_FORMAT",
    "AUTHORING_TRANSACTION_FORMAT",
    "ACTIVATION_GENERATION_FORMAT",
    "CONFIG_GENERATION_FORMAT",
    "SECRET_GENERATION_FORMAT",
    "SECRET_STATUS_FORMAT",
    "SELECTED_POINTER_FORMAT",
    "SELECTION_TRANSACTION_FORMAT",
    "STORE_FORMAT",
    "ActivationGeneration",
    "BundleManifest",
    "BundleValidationError",
    "CandidateInspection",
    "CONFIGURATION_BOOTSTRAP_ENV_NAMES",
    "STANDARD_INSTALLATION_ENV",
    "AccessConfiguration",
    "AUTHORED_REVISION_PREFIX",
    "AuthoredCandidateSnapshot",
    "AuthoredRevisionConflict",
    "AuthoringModeError",
    "AuthoringMutationError",
    "AuthoringMutationResult",
    "AuthoringMutationUnavailable",
    "CandidateReview",
    "BrainConfiguration",
    "BundleRoleError",
    "BundleRoleInventory",
    "ConfigurationSyntaxError",
    "ConfigurationFinding",
    "ConfigurationCanonicalizationError",
    "ConfigurationBootstrapError",
    "ConfigurationBootstrapSettings",
    "load_standard_installation_effective_config",
    "ConfigGeneration",
    "GenerationCompatibilityError",
    "EffectiveConfig",
    "BrainRuntimeSettings",
    "BrainEffectiveRuntimeSettings",
    "BrainCoreRuntimeConsumers",
    "SelectedInferenceConfiguration",
    "SelectedSttConfiguration",
    "SelectedTtsConfiguration",
    "HouseholdRuntimeSettings",
    "AccessRuntimeSettings",
    "SourceCredentialBindingSettings",
    "SatelliteBrainEdgeSettings",
    "SatelliteFleetRuntimeSettings",
    "SatelliteUiRuntimeEntry",
    "SatelliteUiRuntimeSettings",
    "FactsRuntimeSettings",
    "InformationRuntimeSettings",
    "NewsRuntimeSettings",
    "NewsSourceRuntimeSettings",
    "SuggestionsRuntimeSettings",
    "MusicRuntimeSettings",
    "AudiobookRuntimeSettings",
    "AudiobookUserAccountSettings",
    "GenerationIntegrityError",
    "GenerationStore",
    "GenerationStoreError",
    "HouseholdConfiguration",
    "HOST_LOCAL_PROTOCOL_FORMAT",
    "HostLocalAuthorizationError",
    "HostLocalConfigurationClient",
    "HostLocalConfigurationServer",
    "HostLocalDispatcher",
    "HostLocalProtocolError",
    "HostLocalServiceAlreadyRunning",
    "BrainConfigurationHostLocalRuntime",
    "BrainConfigurationStartup",
    "StandardBrainConfigurationHostLocalRuntime",
    "StandardUnixPeerAuthorizer",
    "UnixPeerCredentials",
    "UnixPeerIdentity",
    "read_unix_peer_credentials",
    "LoadedBundle",
    "NormalizedBundle",
    "ProvenanceEntry",
    "PROJECTION_REVISION_PREFIX",
    "PROJECTION_SCHEMA_VERSION",
    "OPTIONAL_ROLE_PATHS",
    "OPTIONAL_ROLE_MODELS",
    "ParsedYamlDocument",
    "REPORT_FORMAT",
    "REQUIRED_ROLE_PATHS",
    "REQUIRED_ROLE_MODELS",
    "CONFIG_FORMAT",
    "CONFIG_REVISION_PREFIX",
    "ROLE_MODELS",
    "RUNTIME_CUTOVER_FORMAT",
    "RUNTIME_CUTOVER_PATH",
    "RestrictedYamlParser",
    "RuntimeCutoverMarker",
    "RuntimeCutoverResult",
    "SatelliteRuntimeCompatibilityAcceptanceResult",
    "GeneratedSatelliteProjection",
    "ControlServiceCompatibility",
    "InteractionRuntimeCompatibility",
    "AcceptedSatelliteRuntimeCompatibility",
    "ProjectedMusicConfiguration",
    "PROJECTION_ACTIVATION_FORMAT",
    "SATELLITE_PROJECTION_PULL_FORMAT",
    "PROJECTION_GENERATION_FORMAT",
    "ProjectionGenerationError",
    "PROJECTION_SECRET_GENERATION_FORMAT",
    "SatellitesConfiguration",
    "SatelliteProjectedConfiguration",
    "SatelliteProjection",
    "SatelliteProjectionActivation",
    "SatelliteProjectionGeneration",
    "SatelliteProjectionGenerationStore",
    "SatelliteProjectionSecretGeneration",
    "ResolvedSatelliteProjection",
    "SatelliteProjectionAuthenticationError",
    "SatelliteProjectionPullEnvelope",
    "SatelliteProjectionResolver",
    "CanonicalPlaybackTargetResolver",
    "PlaybackTargetResolutionError",
    "ResolvedPlaybackTarget",
    "EPHEMERAL_HTTP_SOURCE_ID",
    "CanonicalRequestSourceResolver",
    "RequestSourceAuthenticationError",
    "ResolvedRequestSource",
    "SatelliteRuntimeCompatibility",
    "SatelliteRuntimeCompatibilityStore",
    "InstalledSatelliteProjection",
    "SemanticChange",
    "SecretCompanionError",
    "SecretGenerationConflict",
    "SecretAlreadyExists",
    "SecretCompanionDrift",
    "SecretGenerationPrunedError",
    "SecretGenerationRevokedError",
    "SecretMutationError",
    "SecretMutationResult",
    "SecretMutationUnavailable",
    "SecretNotFound",
    "SecretRemovalBlocked",
    "SafetyAcknowledgementRequired",
    "SelectedGenerationChanged",
    "SecretReferenceUse",
    "SecretSnapshot",
    "SelectionCommittedAuditPending",
    "SelectionRecoveryAmbiguous",
    "SelectionTransactionEnvelope",
    "SelectionTransactionJournal",
    "SecretGeneration",
    "SelectedActivation",
    "StoreLineageConflict",
    "StoreLockTimeout",
    "TransitionActivationBlocked",
    "TransitionValidationContext",
    "TransitionValidationResult",
    "ServicePresenceLock",
    "ValidationReport",
    "VALIDATION_VERSION",
    "arm_runtime_cutover",
    "load_effective_config",
    "load_runtime_cutover_marker",
    "runtime_cutover_required",
    "generate_satellite_projection",
    "resolve_brain_configuration_startup",
    "CandidateActivationBlocked",
    "ConfigurationService",
    "ConfigurationStatus",
    "ConfigurationTransactionResult",
    "ExclusiveStoreLock",
    "collect_provenance",
    "access_schema_field_paths",
    "collect_secret_references",
    "assert_authored_revision",
    "discover_bundle_roles",
    "load_bundle",
    "load_bundle_snapshot",
    "load_bundle_snapshot_structure",
    "load_secret_companion",
    "inspect_candidate",
    "canonicalize_json",
    "classify_access_safety",
    "candidate_role_text",
    "intrinsic_access_acknowledgements",
    "normalize_bundle",
    "parse_secret_companion",
    "semantic_diff",
    "snapshot_candidate",
    "start_brain_configuration_host_local_runtime",
    "validate_secret_snapshot",
    "validate_required_role",
    "validate_role",
    "validate_loaded_bundle",
    "validate_configuration_transition",
]
